### ISSUE TITLE
Can't change model

### ISSUE THREAD

**Issue by tariqyasin** [kardolus/chatgpt-cli#11]
Hello. I can't change from chatgpt-3 to 4. I have checked using openAI python tool that I have access to gpt-4.

`local:.chatgpt-cli yasin$ chatgpt -l
Available models:
- gpt-3.5-turbo-0613
- gpt-4-0314
- gpt-4-0613
* gpt-4 (current)
- gpt-3.5-turbo-instruct-0914
- gpt-3.5-turbo-instruct
- gpt-3.5-turbo-0301
- gpt-3.5-turbo-16k
- gpt-3.5-turbo
- gpt-3.5-turbo-16k-0613
local:.chatgpt which model are you
As an AI developed by OpenAI, I don't have a specific model number. I'm based on the GPT-3 (Generative Pretrained Transformer 3) architecture. My primary function is to assist and facilitate efficient communication.`

Not sure how I should go about debugging this.

**Comment by kardolus** [comment]
Hi @tariqyasin! Thanks for submitting the issue and providing feedback.

Did you encounter an error with the `--set-model` command?

I tried reproducing your issue. I may be missing something, but it appears to be working:
```
 2023-09-26 20:35:48 ⌚  Guillermos-MacBook-Pro in ~/workspace/chatgpt-cli
± |main {3} ✓| → chatgpt -v
ChatGPT CLI version v1.3.2 (commit 1c073b18b87914c37c2ae0b624ae5e95b52c5965)
```
```
 2023-09-26 20:35:31 ⌚  Guillermos-MacBook-Pro in ~/workspace/chatgpt-cli
± |main {3} ✓| → chatgpt -l
Available models:
- gpt-3.5-turbo-0613
- gpt-4-0314
- gpt-4-0613
* gpt-4 (current)
- gpt-3.5-turbo-instruct-0914
- gpt-3.5-turbo-instruct
- gpt-3.5-turbo-0301
- gpt-3.5-turbo-16k
- gpt-3.5-turbo
- gpt-3.5-turbo-16k-0613

 2023-09-26 20:35:34 ⌚  Guillermos-MacBook-Pro in ~/workspace/chatgpt-cli
± |main {3} ✓| → chatgpt --set-model gpt-4-0613
Model successfully updated to gpt-4-0613

 2023-09-26 20:35:45 ⌚  Guillermos-MacBook-Pro in ~/workspace/chatgpt-cli
± |main {3} ✓| → chatgpt -l
Available models:
- gpt-3.5-turbo-0613
- gpt-4-0314
* gpt-4-0613 (current)
- gpt-4
- gpt-3.5-turbo-instruct-0914
- gpt-3.5-turbo-instruct
- gpt-3.5-turbo-0301
- gpt-3.5-turbo-16k
- gpt-3.5-turbo
- gpt-3.5-turbo-16k-0613
```

**Comment by kardolus** [comment]
Here's the unit test that verifies that the model is changed as expected:

https://github.com/kardolus/chatgpt-cli/blob/5c3206fbdc4ea918035941480384e3a23a3f7af3/client/client_test.go#L196

I am going to close this issue since I am unable to reproduce it. Feel free to reopen it with an example. An action item for me is to add a `--debug` flag that shows the actual callouts and responses to and from OpenAI.
