### ISSUE TITLE
HTTP error 429

### ISSUE THREAD

**Issue by ChrisJan00** [kardolus/chatgpt-cli#13]
I just downloaded the program with
`curl -L -o chatgpt https://github.com/kardolus/chatgpt-cli/releases/download/v1.3.2/chatgpt-linux-amd64`
set up my API key, and run it with a first query.  I get the error message:
`http error: 429`

System: Linux Mint 21.2 Cinnamon
I am using the free tier of chatgpt (3.5), if that is relevant.

**Comment by kardolus** [comment]
Hi Chris! 

A `429` is typically returned by the OpenAI API for exceeding the rate limit
or for hitting the maximum monthly spend. 

Could you perhaps check your key usage dashboard? https://platform.openai.com/account/usage

I imagine the free version has a lower token limit, however, I have not experimented with the free version of the API.

**Comment by ChrisJan00** [comment]
Ah, I see.  It seems to be the case.  The "free" tier is only valid for a short period when you sign up. Afterwards, I guess you'd have to create a new account every time.  Thanks for the clarification.
