### ISSUE TITLE
Escape chars

### ISSUE THREAD

**Issue by p4-k4** [kardolus/chatgpt-cli#14]
Is there a preferred way to provide escape characters especially in cases where we want to provide multi-line code snippets with the prompt?

Cheers and thanks!

**Comment by kardolus** [comment]
Hi! The preferred way right now would be to use a pipe. For example, if I have multiple lines stored in my paste buffer I could do: 

```
echo $(pbpaste) | chatgpt what can you tell me about this error?
```

Or you could cat a multiline file: 

```
cat filename.txt | chatgpt give me the tldr of this file
```

From a UX perspective, is there a specific feature you have in mind for supporting multiline input? I was thinking perhaps there could be a multiline command flag (which would wait for 'EOF'). I feel like there could be a solution that is more user friendly possible though.

**Comment by p4-k4** [comment]
Hey there,

I'm currently using your second approach but it can become quite tedious. I would prefer pasting over supplying a file too.

With single or multiline in mind, it might be nice to rather than using a pipe, perhaps we could use an `append` flag:

```bash
chatgpt -a "provide dart documentation comments for this piece of code"

Enter the string to append to the prompt:

main() => print('Hi mum!');
````

Where `-m` will cache the AI prompt string, then the CLI prompts/waits for us to enter a string either being single or multiline. I'm using vi mode w/ zsh so it might be nice to allow for a second chance to edit the code rather than waiting/triggering on EOF.

A small benefit of this is that we get shell session history to refer back to and can actually see code/multiline that was previously sent, in a somewhat structured/clean way. It could be useful for not only code but anything "append-able".

There's some other improvements I would like to suggest for session handling and syntax highlighting, perhaps I could put those in separate issues?

Sorry, I'm not go adept otherwise would totally contribute - this program has helped me a lot thank you.

Cheers

**Comment by kardolus** [comment]
Thanks! I like this idea! 

I'm inclined towards implementing this. However, I'm curious about your thoughts on signaling the end of a multi-line input. Would a specific delimiter (like EOF) or a sequence (such as two consecutive Enter presses) be intuitive from a user's perspective?

**Comment by p4-k4** [comment]
If it were me, I'd just allow for Enter to be pressed as normal. This would allow for further editing in the shell before we submit the "appendable" text to the prompt. Look forward to it! Thanks.

**Comment by kardolus** [comment]
You got it. I am thinking about perhaps allowing multiline input in the current interactive-mode (`chatgpt -i`). But `-a` could work as well. 

Just in case you are not aware, in bash you can do this already:
```
 2023-10-07 10:13:02 ⌚  Guillermos-MacBook-Air in ~/workspace
○ → chatgpt 'what is
the capital
of the netherlands?'
The capital of the Netherlands is Amsterdam.
```

Will keep you posted on the progress!
