### ISSUE TITLE
http error: 429

### ISSUE THREAD

**Issue by xsoulp** [kardolus/chatgpt-cli#15]
Everytime i try a query, i get  a 429. 
nothing more is said

**Comment by kardolus** [comment]
Actually, could you share the output of that `curl` in case you are still having a `429`. Would be a great test case :).

**Comment by kardolus** [comment]
Never mind, fixed this in 1.3.3: https://github.com/kardolus/chatgpt-cli/releases/tag/v1.3.3

**Comment by xsoulp** [comment]
Thanks for your help.
I found out the problem using the curl command you provided

"error": {
        "message": "You exceeded your current quota, please check your plan
and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }

It seems my free plan doesn't allow me to use the api? I never use it

**Comment by kardolus** [comment]
Thanks for sharing the error message! I didn't know the free plan didn't allow for API usage. That's a bummer.

**Comment by no1etal** [comment]
I have a paid plan and am also getting such error. On Openai API keys [website](https://platform.openai.com/account/api-keys), it says I have never used the API key even though I have tried a chatgpt-cli query
