### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by thesofakillers** [kardolus/chatgpt-cli#2]
How does one uninstall this?

**Comment by kardolus** [comment]
Remove the binary. 

Type: `which chatgpt` to locate it (likely `sudo rm /usr/local/bin/chatgpt`). In case you created a folder in your home dir you will have to remove that too (`rm -rf ~/.chatgpt-cli`).

I will create a section in the readme for this.

**Comment by kardolus** [comment]
@thesofakillers here's a link to the Uninstallation section: https://github.com/kardolus/chatgpt-cli#uninstallation
