### ISSUE TITLE
OPENAI KEY

### ISSUE THREAD

**Issue by TimeToCrack** [kardolus/chatgpt-cli#24]
so i just installed this that ms copilot told me to do so i can have chatgpt and it says: missing environment variable: OPENAI_API_KEY how am i gonna solve this?

**Comment by kardolus** [comment]
Hi there. Thanks for installing!

You'll need an API key --> https://platform.openai.com/account/api-keys

You'll also need to setup your environment: 
```
export OPENAI_API_KEY="your_api_key"
```

**Comment by kardolus** [comment]
@TimeToCrack closing this issue. Please re-open if you still have issues using the cli.
