### ISSUE TITLE
Plans to add `--set-thread` and `--list-threads` flags ?

### ISSUE THREAD

**Issue by angustatchell** [kardolus/chatgpt-cli#25]
Hi @kardolus , 

Thanks for your work putting this CLI together. It's so nice to use ChatGPT in such a simple way. (And great to use in situations where browsers are disabled, like when using restricted airplane "message only wifi" packages !)

Having used it for a couple of days now, I'm finding the most UX friction to be in changing the threads. The simplest way I have been doing this from the command line is with sed on the config file.

Do you have any plans to add a `--set-thread` flag, and beyond that, a `--list-threads` flag?

I think these would make a really positive impact on the UX.

All the best,
Angus

**Comment by kardolus** [comment]
@angustatchell I haven't thought of this. I think this is a great idea. Thank you. 

Currently you can set thread using the `OPENAI_THREAD` environment variable or through your `config.yaml` file. 

However, having flags to actually set them would be great. I will think about the implementation.

**Comment by kardolus** [comment]
@angustatchell I added the `--set-thread` flag in [this commit](https://github.com/kardolus/chatgpt-cli/commit/f22df8793edc9af6ad4d09325297b23aca8d4c96).

I will try to find some time later today to add `--list-threads`. I may end up waiting until next weekend :).

Either way, I will cut a new release (`1.4.1`) after adding the `--list-threads` flag. I will keep you in the loop.

**Comment by angustatchell** [comment]
@kardolus awesome!

Looking forward to giving it a try.

**Comment by kardolus** [comment]
@angustatchell just released `1.4.1` with the new flags :)
