### ISSUE TITLE
`config.yaml`'s comments should be preserved when being written

### ISSUE THREAD

**Issue by nopeless** [kardolus/chatgpt-cli#37]
a nice qol because I hand edit the yaml a lot and add comments

**Comment by kardolus** [comment]
@nopeless great point. I will look into this!

**Comment by kardolus** [comment]
@nopeless fixed this in version v1.5.2 :) 

It was kinda fun to work on. Never done low level yaml reading/writing before. Let me know if you encounter any issues.
