### ISSUE TITLE
Error message should not go to stdout

### ISSUE THREAD

**Issue by gzqx** [kardolus/chatgpt-cli#45]
Currently, if I redirect output of chatgpt-cli to a file as
```
chatgpt "1+1" >> output
```
If an error occurs, e.g. internet connection goes wrong, the error message will go to the file.

**Comment by kardolus** [comment]
That's a great point! Fixed it in this commit: https://github.com/kardolus/chatgpt-cli/commit/675a74627a067f1dacef31b4a541108a42775559

Will cut a new release tonigh.
