### ISSUE TITLE
Auto-create new thread per conversation like in ChatGPT

### ISSUE THREAD

**Issue by oluckyman** [kardolus/chatgpt-cli#49]
It would be nice to have a mode similar to ChatGPT that, by default, starts the interactive mode in a new thread rather than in the default one.
This way, I can quickly create random conversations with a few questions. 
Currently, I don't see how to quickly start a conversation in a new thread (and I don't yet know if it's a throwaway thread or one I might want to return to).

**Comment by catskull** [comment]
Happy to help out on this one @kardolus

**Comment by kardolus** [comment]
Thanks @catskull! Sorry y'all, was busy working on `1.6.1`.

@oluckyman this seems like a good idea. Is there a specific naming convention you have in mind? I could try naming the thread based on the first query (?).

**Comment by oluckyman** [comment]
How about using a short, two-word slug? This could be either randomly generated or based on the thread content.

**Comment by kardolus** [comment]
A two-world slug sounds good, I will start with randomly created ones since it is easier to implement. We can always iterate later. Will probably make it configurable with a simple variable so users can opt in for this new functionality.

**Comment by kardolus** [comment]
@oluckyman I finally have time and energy again :). Just implemented this! --> https://github.com/kardolus/chatgpt-cli/commit/e9756499a4c5c276077228b750da56285b04d173

I will cut a release this weekend. Sorry to keep you waiting for so long.

**Comment by kardolus** [comment]
```
 2024-08-16 10:18:30 ⌚ (☸️ |kind:N/A) Guillermos-MacBook-Pro in ~/workspace/chatgpt-cli
± |main ↑1 {1} ✓| → ./bin/chatgpt --interactive
Entering interactive mode. Using thread 'int_28ee'. Type 'exit' and press Enter or press Ctrl+C to quit.

[2024-08-16 10:18:34] [Q1] ok
How can I help you today?
```
