### ISSUE TITLE
32 bit's support

### ISSUE THREAD

**Issue by Nehc** [kardolus/chatgpt-cli#51]
This tool will be especially cool on ancient devices where there is nothing but the CLI. But now it does not run on the Eee PC 900, as I understand it because it is a 32-bit platform. I could probably compile it myself from the sources, but... I need more instructions - I'm not an expert in this. )

**Comment by kardolus** [comment]
@Nehc ahh interesting. I have not thought about that use case yet. I created a 32 bit linux binary. Any chance you could test it out on your Eee PC 900?

https://github.com/kardolus/chatgpt-cli/releases/download/v1.6.1/chatgpt-linux-386

**Comment by kardolus** [comment]
This may take me a few iterations to get right btw. I may have to disable CGO (static linking)

**Comment by Nehc** [comment]
It's work! coool. Grats! )

**Comment by kardolus** [comment]
Yay, that's awesome. Thank you for testing. Just added the linux 386 binary to the script for future releases and updated the readme.
