### ISSUE TITLE
listModule interface design suggestions

### ISSUE THREAD

**Issue by zzerding** [kardolus/chatgpt-cli#55]
### Description:
> Currently, the ⁠listModule interface in Litelm uses the “gpt” prefix for all models. This makes it difficult to identify and use models other than GPT models.

### Proposed Solutions:
1.	Remove the “gpt” prefix: This would make the interface more inclusive and allow users to easily identify all available models.
2.	Use parameters: Instead of hardcoding the “gpt” prefix, using a parameter to specify the model type would provide more flexibility and clarity. This would allow users to filter models based on specific criteria, such as model family or provider.

### Expected Outcome:
Implementing one of these solutions would improve the user experience by:
	•	Providing a clear and consistent interface for listing models.
	•	Allowing users to easily identify and utilize models other than GPT models.
	•	Enhancing the overall flexibility and usability of the ⁠listModule interface.

**Comment by kardolus** [comment]
@zzerding thanks for the suggestion! I am busy this weekend but am off all of next week. Will look into it!

**Comment by kardolus** [comment]
@zzerding is there any change you could provide a permalink? There's no `listModule` interface in the code.

**Comment by zzerding** [comment]
[https://github.com/kardolus/chatgpt-cli/blob/main/client/client.go#L82](https://github.com/kardolus/chatgpt-cli/blob/main/client/client.go#L82)
For example, the litellm openai compatible interface model list I configured includes gpt-* gemini-* . `gptchat -l` can only list gpt models.
My branch does not manage vendors, so I cannot give PR. You can refer to this commit.[https://github.com/zzerding/chatgpt-cli/commit/03cc0bf1e907af54b14f964efa2705b85479accd#diff-bd3a55a72186f59e2e63efb4951573b2f9e4a7cc98086e922b0859f8ccc1dd09L82](https://github.com/zzerding/chatgpt-cli/commit/03cc0bf1e907af54b14f964efa2705b85479accd#diff-bd3a55a72186f59e2e63efb4951573b2f9e4a7cc98086e922b0859f8ccc1dd09L82)
