### ISSUE TITLE
New Line in interactive mode

### ISSUE THREAD

**Issue by mandulaj** [kardolus/chatgpt-cli#59]
Love this tool! Is there a way though to write the prompts across multiple lines into the interactive mode. I tried `Shift-Enter` `Ctrl-Enter` but all of them submit the prompt....

**Comment by kardolus** [comment]
@mandulaj This is a good point! It's not supported. I will look into it.

**Comment by kardolus** [comment]
I played around with the current library: github.com/chzyer/readline

But unfortunately it cannot detect `SHIFT`. I would have to write my own low level input handling which would not be portable across platforms or even shells within the same platform (eg zsh vs bash on a Mac). 

Will try to come up with something. I really like the idea, but I am sceptic that I can come up with a solution anytime soon.
