### ISSUE TITLE
Option to remove line-by-line animation?

### ISSUE THREAD

**Issue by stephen010x** [kardolus/chatgpt-cli#61]
When using this client, it becomes really nauseating for me when the text is printing out line by line. I would much prefer if there is an option to just have it print it all out at once to save me the downtime, and for it to be a bit easier on the eyes. Do you suppose we could make this a feature?

**Comment by kardolus** [comment]
This feature already exists. It's the `--query` flag. Ie. `chatgpt --query what is the capital of france`

**Comment by stephen010x** [comment]
> This feature already exists. It's the `--query` flag. Ie. `chatgpt --query what is the capital of france`

Thank you! 
Sorry I didn't realize that is what the --query flag did. I should have read the documentation a bit closer.

**Comment by stephen010x** [comment]
@kardolus 
I notice that there is a significantly delay when I use the `--query` flag. It takes about as long as it would for the message to finish printing without the `--query` flag. Is this just something related to the ChatGPT API?
