### ISSUE TITLE
question: any suggestions for live markdown rendering?

### ISSUE THREAD

**Issue by devidw** [kardolus/chatgpt-cli#63]
tried glow and mdcat on macos but both don't seem to support streaming

**Comment by kardolus** [comment]
@devidw I haven't found anything that works for live markdown rendering. But this is a Go program that does markdown rendering: https://github.com/MichaelMure/go-term-markdown. 

I was thinking of looking at the code. I am not sure how much work it would be to implement something like that into the CLI.

**Comment by devidw** [comment]
gotcha, ya i could not find anything either

for now i was able to hack something together by piping into this script, which uses glow and clears the output before each render: https://github.com/charmbracelet/glow/issues/601#issuecomment-2100838870

**Comment by kardolus** [comment]
@devidw I finally did a deep dive into this :). I was inspired by that hack you shared and created a smoother script here: 

https://github.com/kardolus/chatgpt-cli/blob/main/scripts/mdrender.sh

Clearing the console in a loop isn't great. My script doesn't do that. It's still a bit of a hack but it's smooth. 

Try 
```
chatgpt write a hello world program in Java | ./scripts/mdrender.sh
```

Let me know what you think!

**Comment by kardolus** [comment]
Fun in combination with the new prompt flag too :) 
```
cat README.md | chatgpt -n --prompt ../prompts/summarize.md | ./scripts/mdrender.sh
```
