### ISSUE TITLE
[Feature Request] Format response header

### ISSUE THREAD

**Issue by SkyaTura** [kardolus/chatgpt-cli#66]
Currently is possible to format the user prompt "header", using `command_prompt: 'user >'`, but there is no equivalent option for indicating the AI answer.

Ideally, we should be able to do something like `print_after_prompt: '\nai > '`.

Or at least add a linebreak after the user prompt.

**Comment by kardolus** [comment]
Ah yeah. This is a good call for sure. I will try to pick this up somewhere this week.

**Comment by kardolus** [comment]
@SkyaTura rolled this out in `ChatGPT CLI v1.6.6`. Note that you do have to single quote your prompt because of the way yaml works. For example

```
output_prompt: '\noutput: '
```

**Comment by SkyaTura** [comment]
Thanks for quickly rolling this out. I'll give it a try soon
