### ISSUE TITLE
Feature Request: Add ``clear`` command to clear the screen in the interactive mode

### ISSUE THREAD

**Issue by zinwang** [kardolus/chatgpt-cli#67]
Hi, I find this tool so great and helpful. It would be fantastic if there were a command to clear the entire screen in interactive mode. This feature would help keep the workspace tidy and organized. 

I can submit a PR for this. What do you think?

Here is a demo video for the concept:

[![IMAGE ALT TEXT](https://i.vimeocdn.com/video/1931809008-aef7ad66867c5b518fafdb18bed4343392faadc6edd902d2b89a3f93060edef2-d_295x166?r=pad)](https://vimeo.com/1013762414)

**Comment by kardolus** [comment]
@zinwang ahh that's clever! I will look into this. Thanks.

**Comment by kardolus** [comment]
@zinwang Done! I verified that it works in `bash`. Hopefully in other shells as well. 

Commit: https://github.com/kardolus/chatgpt-cli/commit/0b55c0b2aef29fc0a3a3ae1e6cc74c4d66725a8b
Release: https://github.com/kardolus/chatgpt-cli/releases/tag/v1.6.8

Please re-open this issue if it doesn't work for you.

**Comment by zinwang** [comment]
Thanks, that works!
