### ISSUE TITLE
Consider adding a flag to change model temporarily

### ISSUE THREAD

**Issue by woerndl** [kardolus/chatgpt-cli#68]
I run almost all of my commands with one of the simple models, but for more complex tasks I sometimes want to use a more advanced model. If I were to use `--set-model` I would have to add it to every command I run (to set and reset), changing the `config.yaml` way more than necessary. Do you think it would make sense to add a flag like `--model` or `--use-model` for single command usage that differs from the default model in the config?

**Comment by kardolus** [comment]
I like this idea. Maybe the configuration should be an array instead of a single config. Then you can "target" a different model on the fly. So you may have different llama, perplexity and chatgpt settings and just switch the model you are targeting rather than having to reset all values. This will be a little tedious to implement so it may take a minute. Great idea though.

**Comment by kardolus** [comment]
@woerndl I totally misread this. For a long time I have been thinking about having a quick way to set the LLM. Not the model :) -- So set llama, perplexity, openai etc. 

Anyway, you can already set the model like this: 
```
OPENAI_MODEL=gpt-3.5-turbo chatgpt who is max verstappen?
```
Is this something that works for you? I am down to create a flag as well if that's easier. It would not be hard to implement.

**Comment by kardolus** [comment]
FYI; Created a new issue here for the LLM targeting: https://github.com/kardolus/chatgpt-cli/issues/74

**Comment by woerndl** [comment]
Thank you for your effort, Guillermo. In my opinion, runtime value overrides are a great addition, especially when working in the terminal where all commands now start with `chatgpt` rather than an environment variable in such cases. Great release!

**Comment by kardolus** [comment]
Thanks for the kind words! I appreciate it. Glad you are liking the new flags.
