### ISSUE TITLE
Incorrect Version in Release Binary

### ISSUE THREAD

**Issue by Xevion** [kardolus/chatgpt-cli#91]
Thought it was kinda odd, is this intended? I really doubt it is.

Platform: Linux AMD64 target, Windows 10 with WSL 2.3.24, Ubuntu 22.04 LTS Jammy

**Test Command** (linux-amd64)

```
curl -L -o chatgpt https://github.com/kardolus/chatgpt-cli/releases/download/v1.7.4/chatgpt-linux-amd64 && chmod +x chatgpt && sudo mv chatgpt /usr/local/bin/ && chatgpt --version
```

**Expected**

Something with `v1.7.4` in it.

**Real Output**

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 9580k  100 9580k    0     0  14.2M      0 --:--:-- --:--:-- --:--:-- 14.2M
ChatGPT CLI version v1.7.3 (commit 5121c3563bfb74bf7e35df6ce492d85bf12e1e0d)
```

**Comment by Xevion** [comment]
If I install with HomeBrew (which I'm thinking might be the better option at this point), the version is correct.

```
$ brew tap kardolus/chatgpt-cli && brew install chatgpt-cli
$ chatgpt -v
ChatGPT CLI version v1.7.4 (homebrew)

**Comment by kardolus** [comment]
It is the correct version, however, I created the binaries before bumping the release tag. Whoops!

```
5121c35  - (HEAD, tag: v1.7.4)
```
Will be more mindful next time!

**Comment by kardolus** [comment]
Fixed this as part of this release: https://github.com/kardolus/chatgpt-cli/releases/tag/v1.7.5
