### ISSUE TITLE
Feature request: Different colors for user and AI text in interactive mode?

### ISSUE THREAD

**Issue by drone1** [kardolus/chatgpt-cli#94]
Customizable color would be nice, but just an idea. I feel like I want some way to be able to quickly parse my text vs. AI text. Right now I find it quite difficult. Thoughts? Thanks.

**Comment by kardolus** [comment]
Fixed in this commit: https://github.com/kardolus/chatgpt-cli/commit/d0222527f40d4f9a3de986e2251d9fc76350fb84

**Comment by drone1** [comment]
Works great for me. Nice work! Thanks!
