### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by omarkosp** [kardolus/chatgpt-cli#95]
I cannot quite understand how i install this on windows

**Comment by omarkosp** [comment]
Error: http status 429: You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.


how can i fix this ?

**Comment by omarkosp** [comment]
do i need to have a paid version of chat gpt  ?

**Comment by kardolus** [comment]
Hi! You don't need a paid version of chat gpt, but you do need to pay for your API key. They changed their billing method a few times. Not sure if it is pre or post pay. Anyway, that's where the error is coming from. Hope you get it resolved!
