### ISSUE TITLE
Add GPT o1 support

### ISSUE THREAD

**Issue by circlesmiler** [kardolus/chatgpt-cli#96]
Would be nice to have support for the new `GPT o1` models.

**Comment by kardolus** [comment]
I'll look into it! Thanks.

**Comment by kardolus** [comment]
A PR was opened regarding this issue: https://github.com/kardolus/chatgpt-cli/pull/98

I am traveling this week and am hoping to close finish this up by the end of the week.

**Comment by kardolus** [comment]
Merged the PR. Will cut a new release now.
