### ISSUE TITLE
Feature request: Role files

### ISSUE THREAD

**Issue by benjamingorman** [kardolus/chatgpt-cli#99]
It would be pretty convenient if commonly used roles could be stored locally in text files and loaded by the tool using a `--role-file` argument.

The alternative right now is either manually typing out the role, or using some shell syntax to load from a file, e.g. `chatgpt --role "$(< ~/roles/python-coder.txt)" ...`

**Comment by kardolus** [comment]
@benjamingorman I like this idea! Thanks.

**Comment by kardolus** [comment]
Added `role-file` support in this commit https://github.com/kardolus/chatgpt-cli/commit/a487fbdfbd927288c1d2f6c4755de72ca237bc22.

I will close this ticket once I cut a new release later this week.

**Comment by kardolus** [comment]
Fix is part of the new release: https://github.com/kardolus/chatgpt-cli/releases/tag/v1.7.7
